<div class="jumbotron">
    <h1>Bem Vindo ao BAG</h1>
    <p>
        Prezado(a) <?php echo $this->user->getNome()?>, você acessou com sucesso o Sistema de Gerenciamento do Banco Ativo de Germoplasma (BAG) da Embrapa Soja.
    </p>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><img src="<?php echo $this->basePath('img/fundo-soja.png'); ?>" style="width: 100%" alt="Fundo"/>
                </p>
            </div>
        </div>
    </div>

</div>
