<?php
    $title = 'Excluir um registro';
    $url   = $this->url('bag/bag', ['action' => 'delete-modal', 'id' => $this->bag->getId()]);
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente desvincular o material da localização 
    "<?php echo $this->escapeHtml($this->bag->getLocalizacao()->getLocalizacao()); ?>"
</p>

<form action="<?php echo $url; ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $this->bag->getId(); ?>" />
    </div>
</form>