<?php
    $this->headScript()->appendFile('/js/inputmask.js', 'text/javascript');
    $this->headScript()->appendFile('/js/jquery.inputmask.js', 'text/javascript');
    $this->headScript()->appendFile('/js/bag-index.js', 'text/javascript');
    $form = $this->form;
?>

<h1>Materiais cadastrados</h1>

<form action="/bag/bag/index" method="get">
    <div class="row">
        <div class="col-md-2">
            <input type="text" class="small" name="cgs" id="cgs" placeHolder="CGS" value="<?php echo (!empty($this->search['cgs'])) ? $this->search['cgs'] : "";?>">
        </div>
        <div class="col-md-2">
            <input type="text" class="small" name="acesso" id="acesso" placeHolder="Acesso" value="<?php echo (!empty($this->search['acesso'])) ? $this->search['acesso'] : "";?>">
        </div>
        <div class="col-md-2">
            <input type="text" class="small" name="origem" id="origem" placeHolder="Origem" value="<?php echo (!empty($this->search['origem'])) ? $this->search['origem'] : "";?>">
        </div>
        <div class="col-md-2">
            <input type="text" class="small" name="localizacao" id="localizacao" placeHolder="Localização" value="<?php echo (!empty($this->search['localizacao'])) ? $this->search['localizacao'] : "";?>">
        </div>
        <div class="col-md-1 text-right">
            <button class="btn-primary btn-sm" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </div>
    </div>
</form>

<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th style="font-size: 13px;">CGS</th>
                <th style="font-size: 13px;">Acesso</th>
                <th style="font-size: 13px;">Subcollection</th>
                <th style="font-size: 13px;">Origem</th>
                <th style="font-size: 13px;">Localização</th>
                <th style="font-size: 13px; text-align: right">Nº sementes</th>
                <th style="font-size: 13px;">Sinonimia</th>
                <th style="font-size: 13px;">Observação</th>
                <th style="font-size: 13px;">Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->bags as $bag): 
                
                if ( $bag->getPesoTotal() > 0 && $bag->getPesoSem() ) {
                    $numeroSementes = $bag->getPesoTotal() * 100 / $bag->getPesoSem();
                } else {
                    $numeroSementes = 0;
                }
                
                ?>
                <tr>
                    <td style="font-size: 13px;"><?php echo $this->escapeHtml($bag->getMaterial()->getCgs()); ?></td>
                    <td style="font-size: 13px;"><?php echo $this->escapeHtml($bag->getMaterial()->getAcesso()); ?></td>
                    <td style="font-size: 13px;"><?php echo (null != $bag->getMaterial()->getEspecie()) ? $this->escapeHtml($bag->getMaterial()->getEspecie()->getGenero()->getDescricao()." ".$bag->getMaterial()->getEspecie()->getDescricao()): ""; ?></td>
                    <td style="font-size: 13px;"><?php echo (null != $bag->getMaterial()->getPassaporte() ? $this->escapeHtml($bag->getMaterial()->getPassaporte()->getOrigem()) : ""); ?></td>
                    <td style="font-size: 13px;"><?php echo (null != $bag->getLocalizacao() ? $this->escapeHtml($bag->getLocalizacao()->getLocalizacao()) : ""); ?></td>
                    <td style="font-size: 13px; text-align: right"><?php echo number_format($numeroSementes, 2,',','.'); ?></td>
                    <td style="font-size: 13px;"><?php echo (null != $bag->getMaterial()->getPassaporte() ? $this->escapeHtml($bag->getMaterial()->getPassaporte()->getSinonimia1()) : ""); ?></td>
                    <td style="font-size: 13px;"><?php echo $this->escapeHtml($bag->getMaterial()->getObservacao()); ?></td>
                    <td>
                        <button id="editarBag" type="button" class="btn btn-primary btn-xs" onclick="editarBag('<?php echo $bag->getMaterial()->getId();?>')">
                        <span class="glyphicon glyphicon-refresh"></span></button>
                    <?php if (count($this->bags) == 1) { ?>
                        <input type="hidden" value="<?php echo $bag->getMaterial()->getId();?>" name="selecao" id="selecao">
                    <?php } else { ?>
                        <input type="hidden" value="0" name="selecao" id="selecao">
                    <?php } ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->bags, 'Elastic', 'bag/partial/paginator', ['route' => 'bag/bag']); ?>
    </span>
</div>


<div class="modal fade " id="BagModal" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Cadastro de bag</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" onclick="fncSalvarBag(this)">Salvar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type='text/javascript'>
    $('#cgs').focus();
</script>
