<?php 
    $tipos = [1 => "Embrapa", 2 => "Fora de Embrapa", 3 => "Exterior"];
    $status = [1 => "Aberto", 2 => "Encerrado"];
?>
<h1>Pedidos cadastrados</h1>
<form action="/bag/pedido/index" method="get">
    <div class="row">
        <div class="col-md-5">
            <input type="text" class="form-control" name="instituicao" id="instituicao" placeHolder="Instituicao" value="<?php echo (!empty($this->search['instituicao'])) ? $this->search['instituicao'] : "";?>">
        </div>
        <div class="col-md-5">
            <input type="text" class="form-control" name="requisitante" id="requisitante" placeHolder="Requisitante" value="<?php echo (!empty($this->search['requisitante'])) ? $this->search['requisitante'] : "";?>">
        </div>
        <div class="col-md-1 text-right">
            <button class="btn-primary btn" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </div>

    </div>
</form>
<hr>
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Número</th>
                <th>Tipo</th>
                <th>Data da retirada</th>
                <th>Instituição</th>
                <th>Requisitante</th>
                <th>Recebedor</th>
                <th>Área</th>
                <th>Observação</th>
                <th>Status</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pedidos as $pedido):?>
                <tr>
                    <td><?php echo $this->escapeHtml($pedido->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($tipos[$pedido->getTipo()]); ?></td>
                    <td><?php echo $this->escapeHtml($pedido->getDataRetirada()->format("d/m/Y"));?></td>
                    <td><?php echo ($this->instituicoes[$pedido->getId()] != '') ? $this->escapeHtml($this->instituicoes[$pedido->getId()]->getRazaoSocial()):"";?></td>
                    <td><?php echo $this->escapeHtml($pedido->getRequisitante());?></td>
                    <td><?php echo $this->escapeHtml($pedido->getRecebedor());?></td>
                    <td><?php echo $this->escapeHtml($pedido->getArea());?></td>
                    <td><?php echo $this->escapeHtml($pedido->getObservacao());?></td>
                    <td><?php echo $this->escapeHtml($status[$pedido->getStatus()]);?></td>

                    <td>
                        
                        <?php if($pedido->getStatus() == 1):?>

                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/pedido', ['action' => 'save', 'id' => $pedido->getId()]) ?>"
                           title="Editar pedido."><span class="glyphicon glyphicon-pencil"></span>
                        </a>

                        <a class="btn btn-primary btn-sm pull-center"
                            href="<?php echo $this->url('bag/pedido', ['action' => 'delete', 'id' => $pedido->getId()]) ?>"
                            title="Excluir pedido."><span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <?php endif;?>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/pedido', ['action' => 'print', 'id' => $pedido->getId()]) ?>"
                           title="Imprimir pedido."><span class="glyphicon glyphicon-print"></span>
                        </a>
                        <?php if ($pedido->getAnexoAtm() != ''):?>
                            <a class="btn btn-primary btn-sm pull-center"
                               href="<?php echo $this->url('bag/pedido', ['action' => 'read-atm', 'id' => $pedido->getId()]) ?>"
                               title="Visualizar ATM."><span class="glyphicon glyphicon-download-alt"></span>
                            </a>
                        <?php endif;?>
                        
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->pedidos, 'Jumping', 'bag/partial/paginator', ['route' => 'bag/pedido']); ?>
    </span>
</div>
<div class="row">
    <a class="btn btn-primary pull-left" href="/bag/pedido/save">Novo registro</a>
</div>

