<?php
$this->headScript()->appendFile('/js/select2.min.js', 'text/javascript');
$this->headScript()->appendFile('/js/inputmask.js', 'text/javascript');
$this->headScript()->appendFile('/js/jquery.inputmask.js', 'text/javascript');

$form = $this->form;

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de instituição</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/bag/instituicao" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('razaoSocial')); ?><br>
                        <?php echo $this->formElement($form->get('razaoSocial')); ?>
                        <?php echo $this->formElementErrors($form->get('razaoSocial')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('nomeFantasia')); ?><br>
                        <?php echo $this->formElement($form->get('nomeFantasia')); ?>
                        <?php echo $this->formElementErrors($form->get('nomeFantasia')); ?>                  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('tipoPessoa')); ?><br>
                        <?php echo $this->formElement($form->get('tipoPessoa')); ?>
                        <?php echo $this->formElementErrors($form->get('tipoPessoa')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('cnpj')); ?><br>
                        <?php echo $this->formElement($form->get('cnpj')); ?>
                        <?php echo $this->formElementErrors($form->get('cnpj')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('inscricaoEstadual')); ?><br>
                        <?php echo $this->formElement($form->get('inscricaoEstadual')); ?>
                        <?php echo $this->formElementErrors($form->get('inscricaoEstadual')); ?>                  
                    </div>
                    
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('cep')); ?><br>
                        <?php echo $this->formElement($form->get('cep')); ?>
                        <?php echo $this->formElementErrors($form->get('cep')); ?>                  
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('endereco')); ?><br>
                        <?php echo $this->formElement($form->get('endereco')); ?>
                        <?php echo $this->formElementErrors($form->get('endereco')); ?>                  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('pais')); ?><br>
                        <?php echo $this->formElement($form->get('pais')); ?>
                        <?php echo $this->formElementErrors($form->get('pais')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('uf')); ?><br>
                        <?php echo $this->formElement($form->get('uf')); ?>
                        <?php echo $this->formElementErrors($form->get('uf')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('cidade')); ?><br>
                        <?php echo $this->formElement($form->get('cidade')); ?>
                        <?php echo $this->formElementErrors($form->get('cidade')); ?>                  
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('bairro')); ?><br>
                        <?php echo $this->formElement($form->get('bairro')); ?>
                        <?php echo $this->formElementErrors($form->get('bairro')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('caixaPostal')); ?><br>
                        <?php echo $this->formElement($form->get('caixaPostal')); ?>
                        <?php echo $this->formElementErrors($form->get('caixaPostal')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('telefone')); ?><br>
                        <?php echo $this->formElement($form->get('telefone')); ?>
                        <?php echo $this->formElementErrors($form->get('telefone')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('telefone2')); ?><br>
                        <?php echo $this->formElement($form->get('telefone2')); ?>
                        <?php echo $this->formElementErrors($form->get('telefone2')); ?>
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('telefone3')); ?><br>
                        <?php echo $this->formElement($form->get('telefone3')); ?>
                        <?php echo $this->formElementErrors($form->get('telefone3')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('email')); ?><br>
                        <?php echo $this->formElement($form->get('email')); ?>
                        <?php echo $this->formElementErrors($form->get('email')); ?>                  
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($form->get('homePage')); ?><br>
                        <?php echo $this->formElement($form->get('homePage')); ?>
                        <?php echo $this->formElementErrors($form->get('homePage')); ?>                  
                    </div>
                </div>
                
                <br>
                <?php echo $this->formElement($form->get('submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    
    $("#cep").inputmask("99999-999");
    $("#telefone").inputmask("(99) 9999-99999");
    $("#telefone2").inputmask("(99) 9999-99999");
    $("#telefone3").inputmask("(99) 9999-99999");
    
    $('#cnpj').focus(function(e) {
        if ($("#tipoPessoa").val() === '1') {
            $("#cnpj").inputmask("99.999.999/9999-99");
        } else {
            $("#cnpj").inputmask("999.999.999-99");
        }
    });
    $("#pais").select2({
        placeHolder: "Selecione o país",
        allowClear: true
    });

    $("#uf").select2({
        placeHolder: "Selecione a UF",
        allowClear: true
    });
    
    $("#pais").change(function() {
        $.ajax({
            url: '/bag/estado/busca?paisId='+$(this).val(),
            type: 'get',
            dataType: 'json',
            success: function(d) {
                var options = "<option value=''>Selecione o Estado</option>"
                $.each(d.estados, function(key, value) {
                   options += "<option value='"+value.id+"'>"+value.descricao+"</option>"
                });
                $("#uf").html(options);
            }
        });
    });

</script>