<?php

namespace DoctrineORMModule\Proxy\__CG__\Bag\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Regeneracao extends \Bag\Entity\Regeneracao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'titulo', 'dataPlantio', 'motivos', 'status', 'itens', 'responsavel', 'caracteristicas', 'casaVegetacao', 'diasLuz', 'safra'];
        }

        return ['__isInitialized__', 'id', 'titulo', 'dataPlantio', 'motivos', 'status', 'itens', 'responsavel', 'caracteristicas', 'casaVegetacao', 'diasLuz', 'safra'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Regeneracao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPlantio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPlantio', []);

        return parent::getDataPlantio();
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivos', []);

        return parent::getMotivos();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getItens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItens', []);

        return parent::getItens();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavel', []);

        return parent::getResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function getCaracteristicas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaracteristicas', []);

        return parent::getCaracteristicas();
    }

    /**
     * {@inheritDoc}
     */
    public function getCasaVegetacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasaVegetacao', []);

        return parent::getCasaVegetacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasLuz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasLuz', []);

        return parent::getDiasLuz();
    }

    /**
     * {@inheritDoc}
     */
    public function getSafra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSafra', []);

        return parent::getSafra();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPlantio($dataPlantio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPlantio', [$dataPlantio]);

        return parent::setDataPlantio($dataPlantio);
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivos($motivos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivos', [$motivos]);

        return parent::setMotivos($motivos);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setItens($itens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItens', [$itens]);

        return parent::setItens($itens);
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsavel($responsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsavel', [$responsavel]);

        return parent::setResponsavel($responsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function setCaracteristicas($caracteristicas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaracteristicas', [$caracteristicas]);

        return parent::setCaracteristicas($caracteristicas);
    }

    /**
     * {@inheritDoc}
     */
    public function setCasaVegetacao($casaVegetacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasaVegetacao', [$casaVegetacao]);

        return parent::setCasaVegetacao($casaVegetacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasLuz($diasLuz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasLuz', [$diasLuz]);

        return parent::setDiasLuz($diasLuz);
    }

    /**
     * {@inheritDoc}
     */
    public function setSafra($safra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSafra', [$safra]);

        return parent::setSafra($safra);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
