<?php
$form = $this->form;
$form->get('descricao')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o grupo aqui'
]);

$form->get('abreviatura')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite a abreviatura aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de grupo</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/bag/tipo-bag" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-8">
                        <?php echo $this->formLabel($form->get('descricao')); ?><br>
                        <?php echo $this->formElement($form->get('descricao')); ?>
                        <?php echo $this->formElementErrors($form->get('descricao')); ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('abreviatura')); ?><br>
                        <?php echo $this->formElement($form->get('abreviatura')); ?>
                        <?php echo $this->formElementErrors($form->get('abreviatura')); ?>                  
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formElement($form->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

