<?php
    $title = 'Excluir um registro';
    $url   = $this->url('bag/material-tipo-bag', ['action' => 'delete-modal', 'id' => $this->materialTipoBag->getId()]);
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir
    "<?php echo $this->escapeHtml($this->materialTipoBag->getTipoBag()->getDescricao()); ?>"
</p>

<form action="<?php echo $url; ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $this->materialTipoBag->getId(); ?>" />
    </div>
</form>