    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Tipo bag</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->material->getTiposBag() as $materialTipoBag): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($materialTipoBag->getTipoBag()->getDescricao()); ?></td>
                    <td><button type="button" class="btn btn-primary btn-xs" onclick="editarTipoBag('<?php echo $materialTipoBag->getId();?>')">
                        <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                        <button type="button" class="btn btn-primary btn-xs" onclick="excluirTipoBag('<?php echo $materialTipoBag->getId();?>')">
                        <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="row">
         <div class="col-md-12">
             <div class="pull-right">
                 <button type="button" class="btn btn-primary btn-xs" onclick="novoTipoBag('<?php echo $this->material->getId();?>')">
                     <span class="glyphicon glyphicon-plus"></span>
                 </button>
             </div>
         </div>
     </div>

