<?php
$form = $this->form;
$form->get('origem')->setAttributes([
    'placeholder' => 'Digite a origem aqui'
]);
$form->get('genealogia')->setAttributes([
    'placeholder' => 'Digite a genealogia aqui'
]);

$form->get('genealogiaDescritiva')->setAttributes([
    'placeholder' => 'Digite a genealogia descritiva aqui'
]);

$form->get('informacao')->setAttributes([
    'placeholder' => 'Digite informações sobre o passaporte aqui'
]);


$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de Passaporte</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/bag/estado" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('origem')); ?><br>
                        <?php echo $this->formElement($form->get('origem')); ?>
                        <?php echo $this->formElementErrors($form->get('origem')); ?>                  
                    </div>
                    
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('genealogia')); ?><br>
                        <?php echo $this->formElement($form->get('genealogia')); ?>
                        <?php echo $this->formElementErrors($form->get('genealogia')); ?>                  
                    </div>

                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('genealogiaDescritiva')); ?><br>
                        <?php echo $this->formElement($form->get('genealogiaDescritiva')); ?>
                        <?php echo $this->formElementErrors($form->get('genealogiaDescritiva')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('sinonimia1')); ?><br>
                        <?php echo $this->formElement($form->get('sinonimia1')); ?>
                        <?php echo $this->formElementErrors($form->get('sinonimia1')); ?>                  
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('sinonimia2')); ?><br>
                        <?php echo $this->formElement($form->get('sinonimia2')); ?>
                        <?php echo $this->formElementErrors($form->get('sinonimia2')); ?>                  
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('sinonimia3')); ?><br>
                        <?php echo $this->formElement($form->get('sinonimia3')); ?>
                        <?php echo $this->formElementErrors($form->get('sinonimia3')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($form->get('informacao')); ?><br>
                        <?php echo $this->formElement($form->get('informacao')); ?>
                        <?php echo $this->formElementErrors($form->get('informacao')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('pais')); ?><br>
                        <?php echo $this->formElement($form->get('pais')); ?>
                        <?php echo $this->formElementErrors($form->get('pais')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('estado')); ?><br>
                        <?php echo $this->formElement($form->get('estado')); ?>
                        <?php echo $this->formElementErrors($form->get('estado')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($form->get('instituicao')); ?><br>
                        <?php echo $this->formElement($form->get('instituicao')); ?>
                        <?php echo $this->formElementErrors($form->get('instituicao')); ?>                  
                    </div>
                </div>


                <br>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

