<input type="hidden" id="pedidoId" name="pedidoId" value="<?php echo $this->pedido->getId();?>">
<table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>CGS</th>
                <th>Acesso</th>
                <th>Sinonimia</th>
                <th>Localização</th>
                <th>Quantidade solicitada</th>
                <th>Quantidade atendida</th>
                <th>Observação</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pedido->getItens() as $item): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($item->getMaterial()->getCgs()); ?></td>
                    <td><?php echo $this->escapeHtml($item->getMaterial()->getAcesso()); ?></td>
                    <td><?php echo (null != $item->getMaterial()->getPassaporte()) ? $this->escapeHtml($item->getMaterial()->getPassaporte()->getSinonimia1()) : "";?></td>
                    <td><?php echo $this->escapeHtml($item->getMaterial()->getBag()->getLocalizacao()->getLocalizacao());?></td>
                    <td><?php echo $this->escapeHtml($item->getQuantidadeSolicitada()); ?></td>
                    <td><?php echo $this->escapeHtml($item->getQuantidadeAtendida()); ?></td>
                    <td><?php echo $this->escapeHtml($item->getObservacao()); ?></td>
                    <td>
                        <?php if ($this->pedido->getStatus() == 1): ?>
                            <button type="button" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Editar item..." onclick="editarItem('<?php echo $item->getId();?>')">
                            <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                            <button type="button" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Excluir item..." onclick="excluirItem('<?php echo $item->getId();?>')">
                            <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;
            if ($this->pedido->getStatus() == 1):
            ?>
                <tr style="background-color: #f0ffff;">
                    <td>
                        <input type="text" class="form-control" placeholder="CGS" name="pesquisaCgs" id="pesquisaCgs" value=""/>
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="Acesso" name="pesquisaAcesso" id="pesquisaAcesso" value=""/>
                    </td>
                    <td colspan="2">
                        <input type="text" class="form-control" placeholder="Sinonimia" name="pesquisaSinonimia" id="pesquisaSinonimia" value=""/>
                    </td>
                    <td colspan="4"></td>
                    <td colspan="1" style="text-align: center;">
                        <button id="addNovoItem" type="button" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Incluir um novo material ao pedido..."onclick="novoItem('<?php echo $this->pedido->getId();?>')">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                        <label class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Carregar lista de materiais a partir de uma planilha..." for="importar"><span class="glyphicon glyphicon-import" ></span>
                            <input type="file" name="importar" style="display:none;" id="importar">
                        </label>
                    </td>
                </tr>
            <?php endif;?>
        </tbody>
    </table>

<script type="text/javascript">
    
    $("#importar").change(function() {
        
        var formData = new FormData();
        formData.append('pedidoId', $("#pedidoId").val());
        formData.append('arquivo', $("#importar")[0].files[0]);

        $.ajax({
            url: '/bag/item-pedido/save-file',
            type: 'post',
            data: formData,
            processData: false,
            contentType: false,
            success: function() {
                location.reload();
            }
        });
    });

    function verificaEnter(e) {
        var code = e.keyCode || e.which;
        if (code === 13) {
            e.preventDefault();
            $("#addNovoItem").click();
        }
    }

    $("#pesquisaCgs").keydown(function(e) {
        verificaEnter(e);
    });
    
    $("#pesquisaAcesso").keydown(function(e) {
        verificaEnter(e);
    });

    $("#pesquisaSinonimia").keydown(function(e) {
        verificaEnter(e);
    });
   
</script>