<input type="hidden" id="materialId" name="materialId" value="<?php echo $this->material->getId();?>">

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Nome do arquivo</th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        <?php //foreach ($this->imagens as $imagem): ?>
            <tr>
                <td><?php //echo $this->escapeHtml($imagem->getNomeMaterial()); ?></td>
                <td>
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="Excluir item..." onclick="excluirItem('<?php// echo $item->getId(); ?>')">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </td>
            </tr>
        <?php //endforeach; ?>
    </tbody>
</table>
<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            <button type="button" class="btn btn-primary btn-xs" onclick="novaImagem('<?php echo $this->material->getId(); ?>')">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>
    </div>
</div>
