<?php
    $title = 'Excluir um registro';
    $url   = $this->url('bag/item-regeneracao', ['action' => 'delete-modal', 'id' => $this->itemRegeneracao->getId()]);
    $this->headTitle($title);
//    $material = $this->itemRegeneracao->getMaterial();
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
   "<?php echo $this->escapeHtml($this->itemRegeneracao->getOrigem()." - ".$this->itemRegeneracao->getEstaca()); ?>"
</p>

<form action="<?php echo $url; ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $this->itemRegeneracao->getId(); ?>" />
    </div>
</form>