<h1>Avaliações cadastradas</h1>
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3 class="panel-title">
            <b>Regeneração:</b> <?php echo $this->regeneracao->getTitulo();?>
            <a class="btn btn-secondary btn-sm pull-right"
                href="/bag/regeneracao/index/<?php echo $this->regeneracao->getId();?>" title="Fechar"><span
                    class="glyphicon glyphicon-remove"></span></a>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Responsável</th>
                    <th>Descritores</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                foreach ($this->avaliacoes as $avaliacao): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($avaliacao->getDataAvaliacao()->format("d/m/Y")); ?></td>
                        <td><?php echo $this->escapeHtml($avaliacao->getResponsavel()->getNome()); ?></td>
                        <td><?php foreach($avaliacao->getCaracteristicas() as $caracteristica):
                            echo $this->escapeHtml($caracteristica->getDescricao()."-".$caracteristica->getNomeCurto())."<br>";
                        endforeach; ?></td>
                        <td><a class="btn btn-primary btn-sm pull-center"
                               href="<?php echo $this->url('bag/avaliacao', ['action' => 'evaluate', 'id' => $avaliacao->getId()]) ?>"
                               title="Avaliar descritores."><span class="glyphicon glyphicon-phone"></span></a>
                            <a class="btn btn-primary btn-sm pull-center"
                               href="<?php echo $this->url('bag/avaliacao', ['action' => 'delete', 'id' => $avaliacao->getId()]) ?>"
                               title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-xs-11">
        <span class="pull-right">
            <?php echo $this->paginationControl($this->avaliacoes, 'Elastic', 'bag/partial/paginator', ['route' => 'bag/avaliacao']); ?>
        </span>
    </div>
</div>

<div class="row">
    <div class="col-xs-11">
        <a class="btn btn-primary pull-left" href=<?php echo $this->url('bag/avaliacao', ['action' => 'save', 'id' => 0, 'idRegeneracao' => $this->regeneracao->getId()]); ?>>Novo registro</a>
    </div>
</div>

