<?php
    $title = 'Excluir um registro';
    $url = $this->url('bag/motivo', ['action' => 'delete', 'id' => $this->motivo->getId()]);
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
    "<?php echo $this->escapeHtml($this->motivo->getDescricao()); ?>"
</p>

<form action="<?php echo $url;?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $this->motivo->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-success" name="del" value="Não" />
    </div>
</form>
