<?php
    $title = 'Excluir um registro';
    $url   = $this->url('bag/regeneracao-caracteristica', ['action' => 'delete-modal', 'idRegeneracao' => $this->regeneracaoCaracteristica->getRegeneracao()->getId()]);
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
    "<?php echo $this->escapeHtml($this->regeneracaoCaracteristica->getCaracteristica()->getNomeCurto()); ?>"
</p>

<form action="<?php echo $url;?>" method="post">
    <div class="form-group">
        <input type="hidden" name="idRegeneracao" value="<?php echo (int) $this->regeneracaoCaracteristica->getRegeneracao()->getId(); ?>" />
        <input type="hidden" name="idCaracteristica" value="<?php echo (int) $this->regeneracaoCaracteristica->getCaracteristica()->getId(); ?>" />
    </div>
</form>