<h1>Controle de numeração cadastrados</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Ano</th>
                <th>Prefixo</th>
                <th>Sequência atual</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach ($this->numeracoes as $numeracao): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($numeracao->getAno()); ?></td>
                    <td><?php echo $this->escapeHtml($numeracao->getPrefixo()); ?></td>
                    <td><?php echo $this->escapeHtml($numeracao->getSequencia()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/numeracao-estaca', ['action' => 'save', 'id' => $numeracao->getAno()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/numeracao-estaca', ['action' => 'delete', 'id' => $numeracao->getAno()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->numeracoes, 'Elastic', 'bag/partial/paginator', ['route' => 'bag/numeracao-estaca']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/bag/numeracao-estaca/save">Novo registro</a>
</div>

