<?php
$form = $this->form;
$form->get('ano')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o ano aqui'
]);

$form->get('sequencia')->setAttributes([
    'class' => 'form-control',
]);

$form->get('prefixo')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o prefixo aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de característica</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/bag/numeracao-estaca" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('ano')); ?><br>
                        <?php echo $this->formElement($form->get('ano')); ?>
                        <?php echo $this->formElementErrors($form->get('ano')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('prefixo')); ?><br>
                        <?php echo $this->formElement($form->get('prefixo')); ?>
                        <?php echo $this->formElementErrors($form->get('prefixo')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('sequencia')); ?><br>
                        <?php echo $this->formElement($form->get('sequencia')); ?>
                        <?php echo $this->formElementErrors($form->get('sequencia')); ?>                  
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

