<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Banco Ativo de Germoplasma (BAG)')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/select2.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.serializeObject.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        
<style>
.dropdown-submenu {
  position: relative;
}

.dropdown-submenu .dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -1px;
}
</style>

<script>
$(document).ready(function(){
  $('.dropdown-submenu a.test').on("click", function(e){
    $(this).next('ul').toggle();
    e.stopPropagation();
    e.preventDefault();
  });
});
</script>

</head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('img/embrapa.png') ?>" height="28" alt="SigRH"/>
                 </a>
                </div>
                <?php if ($this->identity() != null):?>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>">Início</a></li>

                                <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Bag<span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="/bag/bag">Atualizar safra/peso dos materiais</a></li>
                                            <li><a href="/bag/material">Cadastro de Material</a></li>
                                            <li><a href="/bag/pedido">Pedido - Retirada de Material</a></li>
                                            <li class="dropdown-submenu">
                                                <a class="test" href="#">Regeneração <span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="/bag/regeneracao">Controle de Regeneração (caderneta)</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                </li>
                                <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Cadastros periféricos<span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="/bag/acao">Ação</a></li>
                                            <li><a href="/bag/caracteristica">Característica</a></li>
                                            <li><a href="/bag/especie">Subcollection</a></li>
                                            <li><a href="/bag/estado">Estado</a></li>
                                            <li><a href="/bag/genero">Gênero</a></li>
                                            <li><a href="/bag/tipo-bag">Grupo</a></li>
                                            <li><a href="/bag/instituicao">Instituição</a></li>
                                            <li><a href="/bag/localizacao">Localização</a></li>
                                            <li><a href="/bag/modulo">Módulo</a></li>
                                            <li><a href="/bag/motivo">Motivo</a></li>
                                            <li><a href="/bag/numeracao-estaca">Numeração estaca</a></li>
                                            <li><a href="/bag/pais">País</a></li>
                                            <li><a href="/bag/passaporte">Passaporte</a></li>
                                            <li><a href="/bag/programa">Programa</a></li>
                                        </ul>
                                </li>
                                <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Administração<b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

                                            <li><a href="/users">Gerenciar usuários</a></li>
                                    </ul>
                                </li>
                                <li><a href="/logout">Sair</a></li>
                        </ul>
                    </div>
                <?php endif;?>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> - Empresa Brasileira de Pesquisa Agropecuária - Embrapa Soja.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
