<h1>Ações cadastradas</h1>
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Código</th>
                <th>Ação</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->acoes as $acao): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($acao->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($acao->getDescricao()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/acao', ['action' => 'save', 'id' => $acao->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/acao', ['action' => 'delete', 'id' => $acao->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->acoes, 'Elastic', 'bag/partial/paginator', ['route' => 'bag/acao']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/bag/acao/save">Novo registro</a>
</div>
