    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Característica</th>
                <th>Valor</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->material->getCaracteristicas() as $materialCaracteristica): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($materialCaracteristica->getCaracteristica()->getNomeCurto()); ?></td>
                    <td><?php echo $this->escapeHtml($materialCaracteristica->getValor()); ?></td>
                    <td><button type="button" class="btn btn-primary btn-xs" onclick="editarCaracteristica('<?php echo $materialCaracteristica->getId();?>')">
                        <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                        <button type="button" class="btn btn-primary btn-xs" onclick="excluirCaracteristica('<?php echo $materialCaracteristica->getId();?>')">
                        <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="row">
         <div class="col-md-12">
             <div class="pull-right">
                 <button type="button" class="btn btn-primary btn-xs" onclick="novaCaracteristica('<?php echo $this->material->getId();?>')">
                     <span class="glyphicon glyphicon-plus"></span>
                 </button>
             </div>
         </div>
     </div>

