<h1>Subcollections cadastradas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Gênero</th>
                <th>Subcollection</th>
                <th>Quantidade Mínima</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->especies as $especie): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($especie->getGenero()->getDescricao()); ?></td>
                    <td><?php echo $this->escapeHtml($especie->getDescricao()); ?></td>
                    <td><?php echo $this->escapeHtml($especie->getQuantidadeMinima()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/especie', ['action' => 'save', 'id' => $especie->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('bag/especie', ['action' => 'delete', 'id' => $especie->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->especies, 'Elastic', 'bag/partial/paginator', ['route' => 'bag/especie']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/bag/especie/save">Novo registro</a>
</div>

